# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Where to find user code.
USER_DIR = .

# Flags passed to the preprocessor.
CPPFLAGS += -I$(USER_DIR)/include

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -Wextra

MAIN = replayer

all : $(MAIN)

clean :
	rm -f $(MAIN) *.o
	
loader.o : $(USER_DIR)/src/loader.c $(USER_DIR)/include/replayer.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/src/loader.c

replayer.o : $(USER_DIR)/src/replayer.c $(USER_DIR)/include/replayer.h
	g++ $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/src/replayer.c

replayer : replayer.o loader.o
	g++ $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@