28
{"args": ["/dir_to_mk"], "parents": [], "stamp": {"begin": 10.0, "elapsed": 1}, "call": "nfsd_proc_mkdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 1, "session_id": 1, "children": [2]}
{"args": ["/dir_to_mk"], "parents": [1], "stamp": {"begin": 20.0, "elapsed": 1}, "call": "nfsd_proc_readdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 2, "session_id": 1, "children": [3]}
{"args": ["/dir_to_readdirplus"], "parents": [2], "stamp": {"begin": 30.0, "elapsed": 1}, "call": "nfsd_proc_mkdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 3, "session_id": 1, "children": [4]}
{"args": ["/dir_to_readdirplus"], "parents": [3], "stamp": {"begin": 40.0, "elapsed": 1}, "call": "nfsd_proc_readdirplus", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 4, "session_id": 1, "children": [5]}
{"args": ["/dir_to_readdirplus"], "parents": [4], "stamp": {"begin": 50.0, "elapsed": 1}, "call": "nfsd_proc_rmdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 5, "session_id": 1, "children": [6]}
{"args": ["/dir_to_mk/path_to_creat", "511"], "parents": [5], "stamp": {"begin": 60.0, "elapsed": 1}, "call": "nfsd_proc_creat", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 6, "session_id": 1, "children": [7]}
{"args": ["/dir_to_mk/path_to_creat", "0"], "parents": [6], "stamp": {"begin": 70.0, "elapsed": 1}, "call": "nfsd_proc_access", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 7, "session_id": 1, "children": [8]}
{"args": ["/dir_to_mk/path_to_creat", "4096", "0", "0"], "parents": [7], "stamp": {"begin": 80.0, "elapsed": 1}, "call": "nfsd_proc_write", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 8, "session_id": 1, "children": [9]}
{"args": ["/dir_to_mk/path_to_creat", "4096", "0", "0"], "parents": [8], "stamp": {"begin": 90.0, "elapsed": 1}, "call": "nfsd_proc_read", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 9, "session_id": 1, "children": [10]}
{"args": ["/dir_to_mk/path_to_creat", "/dir_to_mk/link"], "parents": [9], "stamp": {"begin": 100.0, "elapsed": 1}, "call": "nfsd_proc_link", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 10, "session_id": 1, "children": [11]}
{"args": ["/dir_to_mk/link", "4096"], "parents": [10], "stamp": {"begin": 110.0, "elapsed": 1}, "call": "nfsd_proc_readlink", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 11, "session_id": 1, "children": [12]}
{"args": ["/dir_to_mk", "/dir_to_mk_renamed"], "parents": [11], "stamp": {"begin": 120.0, "elapsed": 1}, "call": "nfsd_proc_rename", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 12, "session_id": 1, "children": [13]}
{"args": ["/dir_to_mk_renamed", "/dir_to_mk_renamed_sl"], "parents": [12], "stamp": {"begin": 130.0, "elapsed": 1}, "call": "nfsd_proc_symlink", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 13, "session_id": 1, "children": [14]}
{"args": ["/node", "420", "0"], "parents": [13], "stamp": {"begin": 130.0, "elapsed": 1}, "call": "nfsd_proc_mknod", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 14, "session_id": 1, "children": [15]}
{"args": ["/path_to_getattr", "511"], "parents": [14], "stamp": {"begin": 140.0, "elapsed": 1}, "call": "nfsd_proc_creat", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 15, "session_id": 1, "children": [16]}
{"args": ["/path_to_getattr"], "parents": [15], "stamp": {"begin": 150.0, "elapsed": 1}, "call": "nfsd_proc_getattr", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 16, "session_id": 1, "children": [17]}
{"args": ["/dir_to_mk_renamed_sl"], "parents": [16], "stamp": {"begin": 160.0, "elapsed": 1}, "call": "nfsd_proc_getattr", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 17, "session_id": 1, "children": [18]}
{"args": ["/thereisnosuchpath"], "parents": [17], "stamp": {"begin": 170.0, "elapsed": 1}, "call": "nfsd_proc_getattr", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 18, "session_id": 1, "children": [19]}
{"args": [], "parents": [18], "stamp": {"begin": 180.0, "elapsed": 1}, "call": "nfsd_proc_fsstat", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 19, "session_id": 1, "children": [20]}
{"args": ["/lookup_parent"], "parents": [19], "stamp": {"begin": 190.0, "elapsed": 1}, "call": "nfsd_proc_mkdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 20, "session_id": 1, "children": [21]}
{"args": ["/lookup_parent/dir_to_lookup"], "parents": [20], "stamp": {"begin": 200.0, "elapsed": 1}, "call": "nfsd_proc_mkdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 21, "session_id": 1, "children": [22]}
{"args": ["/lookup_parent/dir_to_lookup"], "parents": [21], "stamp": {"begin": 210.0, "elapsed": 1}, "call": "nfsd_proc_lookup", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 22, "session_id": 1, "children": [23]}
{"args": ["/lookup_parent/dir_to_lookup/to_remove", "511"], "parents": [22], "stamp": {"begin": 220.0, "elapsed": 1}, "call": "nfsd_proc_creat", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 23, "session_id": 1, "children": [24]}
{"args": ["/lookup_parent/dir_to_lookup/to_remove"], "parents": [23], "stamp": {"begin": 230.0, "elapsed": 1}, "call": "nfsd_proc_remove", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 24, "session_id": 1, "children": [25]}
{"args": ["/path_to_commit", "511"], "parents": [24], "stamp": {"begin": 240.0, "elapsed": 1}, "call": "nfsd_proc_creat", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 25, "session_id": 1, "children": [26]}
{"args": ["/path_to_commit", "4096", "0", "0"], "parents": [25], "stamp": {"begin": 250.0, "elapsed": 1}, "call": "nfsd_proc_write", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 26, "session_id": 1, "children": [27]}
{"args": ["/path_to_commit"], "parents": [26], "stamp": {"begin": 260.0, "elapsed": 1}, "call": "nfsd_proc_commit", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 27, "session_id": 1, "children": [28]}
{"args": ["/path_to_commit"], "parents": [27], "stamp": {"begin": 270.0, "elapsed": 1}, "call": "nfsd_proc_setattr", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 28, "session_id": 1, "children": []}
