{"args": ["/dir_to_mk"], "parents": [], "stamp": {"begin": 10.0, "elapsed": 1}, "call": "nfsd_proc_mkdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 1, "session_id": 1, "children": []}
{"args": ["/dir_to_mk"], "parents": [], "stamp": {"begin": 20.0, "elapsed": 10}, "call": "nfsd_proc_readdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 2, "session_id": 1, "children": []}
{"args": ["/dir_to_readdirplus"], "parents": [], "stamp": {"begin": 30.0, "elapsed": 1}, "call": "nfsd_proc_mkdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 3, "session_id": 1, "children": []}
{"args": ["/dir_to_readdirplus"], "parents": [], "stamp": {"begin": 40.0, "elapsed": 10}, "call": "nfsd_proc_readdirplus", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 4, "session_id": 1, "children": []}
{"args": ["/dir_to_readdirplus"], "parents": [], "stamp": {"begin": 50.0, "elapsed": 1}, "call": "nfsd_proc_rmdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 5, "session_id": 1, "children": []}
{"args": ["/dir_to_mk/path_to_creat", "511"], "parents": [], "stamp": {"begin": 60.0, "elapsed": 10}, "call": "nfsd_proc_creat", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 6, "session_id": 1, "children": []}
{"args": ["/dir_to_mk/path_to_creat", "0"], "parents": [], "stamp": {"begin": 70.0, "elapsed": 1}, "call": "nfsd_proc_access", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 7, "session_id": 1, "children": []}
{"args": ["/dir_to_mk/path_to_creat", "4096", "0", "0"], "parents": [], "stamp": {"begin": 80.0, "elapsed": 10}, "call": "nfsd_proc_write", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 8, "session_id": 1, "children": []}
{"args": ["/dir_to_mk/path_to_creat", "4096", "0", "0"], "parents": [], "stamp": {"begin": 90.0, "elapsed": 1}, "call": "nfsd_proc_read", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 9, "session_id": 1, "children": []}
{"args": ["/dir_to_mk/path_to_creat", "/dir_to_mk/link"], "parents": [], "stamp": {"begin": 100.0, "elapsed": 10}, "call": "nfsd_proc_link", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 10, "session_id": 1, "children": []}
