29
{"args": ["/dir_to_mk"], "parents": [], "stamp": {"begin": 10.0, "elapsed": 1}, "call": "nfsd_proc_mkdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 1, "session_id": 1, "children": []}
{"args": ["/dir_to_mk"], "parents": [], "stamp": {"begin": 20.0, "elapsed": 1}, "call": "nfsd_proc_readdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 2, "session_id": 1, "children": []}
{"args": ["/dir_to_readdirplus"], "parents": [], "stamp": {"begin": 30.0, "elapsed": 1}, "call": "nfsd_proc_mkdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 3, "session_id": 1, "children": []}
{"args": ["/dir_to_readdirplus"], "parents": [], "stamp": {"begin": 40.0, "elapsed": 1}, "call": "nfsd_proc_readdirplus", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 4, "session_id": 1, "children": []}
{"args": ["/dir_to_readdirplus"], "parents": [], "stamp": {"begin": 50.0, "elapsed": 1}, "call": "nfsd_proc_rmdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 5, "session_id": 1, "children": []}
{"args": ["/dir_to_mk/path_to_creat", "511"], "parents": [], "stamp": {"begin": 60.0, "elapsed": 1}, "call": "nfsd_proc_creat", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 6, "session_id": 1, "children": []}
{"args": ["/dir_to_mk/path_to_creat", "0"], "parents": [], "stamp": {"begin": 70.0, "elapsed": 1}, "call": "nfsd_proc_access", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 7, "session_id": 1, "children": []}
{"args": ["/dir_to_mk/path_to_creat", "4096", "0", "0"], "parents": [], "stamp": {"begin": 80.0, "elapsed": 1}, "call": "nfsd_proc_write", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 8, "session_id": 1, "children": []}
{"args": ["/dir_to_mk/path_to_creat", "4096", "0", "0"], "parents": [], "stamp": {"begin": 90.0, "elapsed": 1}, "call": "nfsd_proc_read", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 9, "session_id": 1, "children": []}
{"args": ["/dir_to_mk/path_to_creat", "/dir_to_mk/link"], "parents": [], "stamp": {"begin": 100.0, "elapsed": 1}, "call": "nfsd_proc_link", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 10, "session_id": 1, "children": []}
{"args": ["/dir_to_mk/link", "4096"], "parents": [], "stamp": {"begin": 110.0, "elapsed": 1}, "call": "nfsd_proc_readlink", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 11, "session_id": 1, "children": []}
{"args": ["/dir_to_mk", "/dir_to_mk_renamed"], "parents": [], "stamp": {"begin": 120.0, "elapsed": 1}, "call": "nfsd_proc_rename", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 12, "session_id": 1, "children": []}
{"args": ["/dir_to_mk_renamed", "/dir_to_mk_renamed_sl"], "parents": [], "stamp": {"begin": 130.0, "elapsed": 1}, "call": "nfsd_proc_symlink", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 13, "session_id": 1, "children": []}
{"args": ["/node", "420", "0"], "parents": [], "stamp": {"begin": 140.0, "elapsed": 1}, "call": "nfsd_proc_mknod", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 14, "session_id": 1, "children": []}
{"args": ["/path_to_getattr", "511"], "parents": [], "stamp": {"begin": 150.0, "elapsed": 1}, "call": "nfsd_proc_creat", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 15, "session_id": 1, "children": []}
{"args": ["/path_to_getattr"], "parents": [], "stamp": {"begin": 160.0, "elapsed": 1}, "call": "nfsd_proc_getattr", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 16, "session_id": 1, "children": []}
{"args": ["/dir_to_mk_renamed_sl"], "parents": [], "stamp": {"begin": 170.0, "elapsed": 1}, "call": "nfsd_proc_getattr", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 17, "session_id": 1, "children": []}
{"args": ["/thereisnosuchpath"], "parents": [], "stamp": {"begin": 180.0, "elapsed": 1}, "call": "nfsd_proc_getattr", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 18, "session_id": 1, "children": []}
{"args": [], "parents": [], "stamp": {"begin": 190.0, "elapsed": 1}, "call": "nfsd_proc_fsstat", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 19, "session_id": 1, "children": []}
{"args": ["/lookup_parent"], "parents": [], "stamp": {"begin": 200.0, "elapsed": 1}, "call": "nfsd_proc_mkdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 20, "session_id": 1, "children": []}
{"args": ["/lookup_parent/dir_to_lookup"], "parents": [], "stamp": {"begin": 210.0, "elapsed": 1}, "call": "nfsd_proc_mkdir", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 21, "session_id": 1, "children": []}
{"args": ["/lookup_parent/dir_to_lookup"], "parents": [], "stamp": {"begin": 220.0, "elapsed": 1}, "call": "nfsd_proc_lookup", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 22, "session_id": 1, "children": []}
{"args": ["/lookup_parent/dir_to_lookup/to_remove", "511"], "parents": [], "stamp": {"begin": 230.0, "elapsed": 1}, "call": "nfsd_proc_creat", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 23, "session_id": 1, "children": []}
{"args": ["/lookup_parent/dir_to_lookup/to_remove"], "parents": [], "stamp": {"begin": 240.0, "elapsed": 1}, "call": "nfsd_proc_remove", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 24, "session_id": 1, "children": []}
{"args": ["/path_to_commit", "511"], "parents": [], "stamp": {"begin": 250.0, "elapsed": 1}, "call": "nfsd_proc_creat", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 25, "session_id": 1, "children": []}
{"args": ["/path_to_commit", "4096", "0", "0"], "parents": [], "stamp": {"begin": 260.0, "elapsed": 1}, "call": "nfsd_proc_write", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 26, "session_id": 1, "children": []}
{"args": ["/path_to_commit"], "parents": [], "stamp": {"begin": 270.0, "elapsed": 1}, "call": "nfsd_proc_commit", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 27, "session_id": 1, "children": []}
{"args": ["/path_to_commit", "40", "666"], "parents": [], "stamp": {"begin": 280.0, "elapsed": 1}, "call": "nfsd_proc_setattr", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 28, "session_id": 1, "children": []}
{"args": ["/path_to_commit", "32", "500"], "parents": [], "stamp": {"begin": 290.0, "elapsed": 1}, "call": "nfsd_proc_setattr", "rvalue": 0, "caller": {"tid": "0", "pid": "0", "uid": "0", "exec": "(nfsd)"}, "id": 29, "session_id": 1, "children": []}
